import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import  QRCode  from 'qrcode'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [username, setUsername] = useState()
  const [src, setSrc] = useState()

  const generate = ()=>{
    // QRCode.toDataURL(`http://github.com/${username}`)
    // .then((val) => setSrc(val))*
    
    QRCode.toDataURL(username).then(setSrc)
  }

  return (
    <>
      <Head>
        <title>PascoApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

        <img src={src} />

        {/* input username field */}
        <input
          className=''
          type="text"
          placeholder='Entrer votre nom'
          value={username}
          onChange={(e)=>setUsername(e.target.value)}
        />

        {/* generate button */}
        <button type='button' onClick={generate}>Generate</button>

      </div>
      
    </>
  )
}
